
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Exclude Files
        run: |
          rm -rf .devcontainer
          rm -rf .github
          rm -rf .vscode
          rm -rf node_modules
          rm -rf .gitignore
          rm -rf package.json
          rm -rf package-lock.json
          rm -rf README.md
      - name: Replace String
        run: sed -i -e "s/GTAG_ID/${{ secrets.GTAG_ID }}/g" index.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: .